# Generated by Django 2.1 on 2020-03-17 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_chair', models.CharField(max_length=100)),
                ('head_of_chair', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_group', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Chairs')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Specialisations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_of_specialisation', models.CharField(max_length=100)),
                ('name_of_specialisation', models.CharField(max_length=1000)),
                ('name_of_profile', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TableOfDisc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_disc', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('sent', 'Отправлено'), ('approved', 'Одобрено'), ('denied', 'На доработку')], default='new', max_length=50)),
                ('educ_comment', models.TextField()),
                ('admin_comment', models.TextField()),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Chairs')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TableOfEducators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=1000)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Chairs')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='tableofdisc',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.TableOfEducators'),
        ),
        migrations.AddField(
            model_name='tableofdisc',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Specialisations'),
        ),
    ]
