# Generated by Django 2.1 on 2020-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0002_auto_20200317_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofdisc',
            name='content',
            field=models.FileField(upload_to='files'),
        ),
    ]
