# Generated by Django 2.2.12 on 2020-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0006_auto_20200412_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofdisc',
            name='content',
            field=models.FileField(upload_to='media/files'),
        ),
    ]
