# Generated by Django 2.1 on 2020-04-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0006_tableofeducators_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofdisc',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.TableOfEducators'),
        ),
    ]
