# Generated by Django 2.2.12 on 2020-04-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0007_auto_20200412_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofdisc',
            name='specialisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpd.Specialisations'),
            preserve_default=False,
        ),
    ]
