# Generated by Django 2.1 on 2020-04-09 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0007_auto_20200409_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableofeducators',
            name='user',
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
