# Generated by Django 2.2.12 on 2020-04-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0008_tableofdisc_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofdisc',
            name='content',
            field=models.FileField(upload_to='files'),
        ),
    ]
