# Generated by Django 2.2.12 on 2020-04-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0009_auto_20200413_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofdisc',
            name='admin_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='content',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='educ_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
