# Generated by Django 2.1 on 2020-04-09 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpd', '0009_tableofeducators_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableofdisc',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='tableofdisc',
            name='order',
        ),
        migrations.AddField(
            model_name='tableofdisc',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableofeducators',
            name='login',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableofeducators',
            name='password',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.TableOfEducators'),
        ),
    ]
