# Generated by Django 2.2.12 on 2020-04-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rpd.models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0011_auto_20200413_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairs',
            options={'ordering': ['id'], 'verbose_name': 'Таблица кафедр', 'verbose_name_plural': 'Таблица кафедр'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'Таблица групп', 'verbose_name_plural': 'Таблица групп'},
        ),
        migrations.AlterModelOptions(
            name='specialisations',
            options={'ordering': ['id'], 'verbose_name': 'Таблица специализаций', 'verbose_name_plural': 'Таблица специализаций'},
        ),
        migrations.AlterModelOptions(
            name='tableofdisc',
            options={'ordering': ['id'], 'verbose_name': 'Таблица дисциплин', 'verbose_name_plural': 'Таблица дисциплин'},
        ),
        migrations.AlterModelOptions(
            name='tableofeducators',
            options={'ordering': ['id'], 'verbose_name': 'Таблица преподавателей', 'verbose_name_plural': 'Таблица преподавателей'},
        ),
        migrations.AddField(
            model_name='tableofeducators',
            name='image',
            field=models.ImageField(blank=True, upload_to=rpd.models.image_folder, verbose_name='Фотография преподователя'),
        ),
        migrations.AlterField(
            model_name='chairs',
            name='head_of_chair',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Заведущий кафедрой'),
        ),
        migrations.AlterField(
            model_name='chairs',
            name='name_of_chair',
            field=models.CharField(max_length=100, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='group',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Chairs', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code_group',
            field=models.CharField(max_length=50, verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Specialisations', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='specialisations',
            name='code_of_specialisation',
            field=models.CharField(max_length=100, verbose_name='Код специализации'),
        ),
        migrations.AlterField(
            model_name='specialisations',
            name='name_of_profile',
            field=models.CharField(max_length=100, verbose_name='Наименование профиля'),
        ),
        migrations.AlterField(
            model_name='specialisations',
            name='name_of_specialisation',
            field=models.CharField(max_length=1000, verbose_name='Наименование специализации'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Chairs', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Файл с РПД'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='educ_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин преподавателя'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='name_of_disc',
            field=models.CharField(max_length=100, verbose_name='Наименование дисциплины'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Specialisations', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('sent', 'Отправлено'), ('approved', 'Одобрено'), ('denied', 'На доработку')], default='new', max_length=50, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='tableofeducators',
            name='chair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.Chairs', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='tableofeducators',
            name='degree',
            field=models.CharField(max_length=1000, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='tableofeducators',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='tableofeducators',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
    ]
