# Generated by Django 2.1 on 2020-04-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0013_auto_20200412_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='text',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tableofdisc',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='tableofdisc',
            name='content',
            field=models.FileField(upload_to='files'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
