# Generated by Django 2.2.12 on 2020-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0013_auto_20200414_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofdisc',
            name='status',
            field=models.CharField(choices=[('Новое', 'Новое'), ('Отправлено', 'Отправлено'), ('Одобрено', 'Одобрено'), ('На доработку', 'На доработку')], default='Новое', max_length=50, verbose_name='статус'),
        ),
    ]
