# Generated by Django 2.1 on 2020-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0016_auto_20200412_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofdisc',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
